// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Details_screen_init(void)
{
    ui_Details = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Details, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Details, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Details, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Details);
    lv_img_set_src(ui_Image1, &ui_img_7_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_x(ui_Image1, -1);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 265);

    ui_Details1 = lv_label_create(ui_Details);
    lv_obj_set_width(ui_Details1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Details1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Details1, 18);
    lv_obj_set_y(ui_Details1, 3);
    lv_label_set_text(ui_Details1, "Details");
    lv_obj_set_style_text_font(ui_Details1, &ui_font_GoogleSansMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

}
