// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Overview_screen_init(void)
{
    ui_Overview = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Overview, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Overview, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Overview, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Overview);
    lv_obj_set_width(ui_Panel1, 110);
    lv_obj_set_height(ui_Panel1, 81);
    lv_obj_set_x(ui_Panel1, 4);
    lv_obj_set_y(ui_Panel1, 32);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x202020), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Overview1 = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_Overview1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Overview1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Overview1, 7);
    lv_obj_set_y(ui_Overview1, 4);
    lv_label_set_text(ui_Overview1, "Overview");
    lv_obj_set_style_text_font(ui_Overview1, &ui_font_GoogleSansMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Charging = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_Charging, 61);
    lv_obj_set_height(ui_Charging, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Charging, 116);
    lv_obj_set_y(ui_Charging, 10);
    lv_label_set_text(ui_Charging, "Discharge");
    lv_obj_set_style_text_color(ui_Charging, lv_color_hex(0x10BC56), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Charging, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Charging, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Charging, &ui_font_GoogleSansMedium13, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_V = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_V, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_V, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_V, 92);
    lv_obj_set_y(ui_V, 44);
    lv_label_set_text(ui_V, "V");
    lv_obj_set_style_text_color(ui_V, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_V, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_V, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_V, &ui_font_GoogleSansMedium22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_A = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_A, 92);
    lv_obj_set_y(ui_A, 82);
    lv_label_set_text(ui_A, "A");
    lv_obj_set_style_text_color(ui_A, lv_color_hex(0xA0A0A0), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_A, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_A, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_A, &ui_font_GoogleSansMedium22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Percantage = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_Percantage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Percantage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Percantage, 227);
    lv_obj_set_y(ui_Percantage, 50);
    lv_label_set_text(ui_Percantage, "%");
    lv_obj_set_style_text_font(ui_Percantage, &ui_font_GoogleSansMedium14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Remaining = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_Remaining, 60);
    lv_obj_set_height(ui_Remaining, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Remaining, 178);
    lv_obj_set_y(ui_Remaining, 67);
    lv_label_set_text(ui_Remaining, "Remaining");
    lv_obj_set_style_text_letter_space(ui_Remaining, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Remaining, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Remaining, &ui_font_GoogleSansMedium12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Voltage = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_Voltage, 80);
    lv_obj_set_height(ui_Voltage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Voltage, 10);
    lv_obj_set_y(ui_Voltage, 30);
    lv_label_set_long_mode(ui_Voltage, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Voltage, "00.00");
    lv_obj_set_style_text_color(ui_Voltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Voltage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Voltage, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Voltage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Voltage, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Voltage, &ui_font_DINMedium34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Current = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_Current, 80);
    lv_obj_set_height(ui_Current, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Current, 9);
    lv_obj_set_y(ui_Current, 67);
    lv_label_set_long_mode(ui_Current, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Current, "00.00");
    lv_obj_set_style_text_color(ui_Current, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Current, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Current, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Current, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Current, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Current, &ui_font_DINMedium34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RSOC = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_RSOC, 50);
    lv_obj_set_height(ui_RSOC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RSOC, 178);
    lv_obj_set_y(ui_RSOC, 28);
    lv_label_set_text(ui_RSOC, "000");
    lv_obj_set_style_text_letter_space(ui_RSOC, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_RSOC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RSOC, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RSOC, &ui_font_DINMedium32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Left = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_Left, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Left, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Left, 217);
    lv_obj_set_y(ui_Left, 13);
    lv_label_set_text(ui_Left, "Left");
    lv_obj_set_style_text_font(ui_Left, &ui_font_GoogleSansMedium10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Capacity = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_Capacity, 40);
    lv_obj_set_height(ui_Capacity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Capacity, -23);
    lv_obj_set_y(ui_Capacity, -12);
    lv_obj_set_align(ui_Capacity, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_Capacity, "00.00");
    lv_obj_set_style_text_letter_space(ui_Capacity, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Capacity, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Capacity, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Capacity, &ui_font_DINMedium16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OK = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_OK, 40);
    lv_obj_set_height(ui_OK, 20);
    lv_obj_set_x(ui_OK, 127);
    lv_obj_set_y(ui_OK, 89);
    lv_label_set_long_mode(ui_OK, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_OK, "OK");
    lv_obj_set_style_text_color(ui_OK, lv_color_hex(0x10BC56), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_OK, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OK, &ui_font_GoogleSansMedium15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_OK, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OK, lv_color_hex(0x00401C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_OK, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_OK, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_OK, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_OK, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WARN = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_WARN, 52);
    lv_obj_set_height(ui_WARN, 20);
    lv_obj_set_x(ui_WARN, 121);
    lv_obj_set_y(ui_WARN, 89);
    lv_label_set_long_mode(ui_WARN, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_WARN, "WARN");
    lv_obj_add_flag(ui_WARN, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_WARN, lv_color_hex(0xE9CA2C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WARN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WARN, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WARN, &ui_font_GoogleSansMedium15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_WARN, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WARN, lv_color_hex(0x564A10), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WARN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_WARN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_WARN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_WARN, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_WARN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FAIL = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_FAIL, 42);
    lv_obj_set_height(ui_FAIL, 20);
    lv_obj_set_x(ui_FAIL, 126);
    lv_obj_set_y(ui_FAIL, 89);
    lv_label_set_long_mode(ui_FAIL, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_FAIL, "FAIL");
    lv_obj_add_flag(ui_FAIL, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_FAIL, lv_color_hex(0xDC3D2E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FAIL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_FAIL, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_FAIL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_FAIL, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FAIL, &ui_font_GoogleSansMedium15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_FAIL, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FAIL, lv_color_hex(0x511611), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FAIL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_FAIL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_FAIL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_FAIL, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_FAIL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_Overview);
    lv_obj_set_width(ui_Arc1, 50);
    lv_obj_set_height(ui_Arc1, 50);
    lv_obj_set_x(ui_Arc1, 122);
    lv_obj_set_y(ui_Arc1, 32);
    lv_arc_set_value(ui_Arc1, 98);
    lv_arc_set_bg_angles(ui_Arc1, 0, 360);
    lv_arc_set_rotation(ui_Arc1, 270);
    lv_obj_set_style_arc_width(ui_Arc1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x009B43), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc1, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_Arc1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ETA = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_ETA, 41);
    lv_obj_set_height(ui_ETA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ETA, 178);
    lv_obj_set_y(ui_ETA, 9);
    lv_label_set_text(ui_ETA, "00:00");
    lv_obj_set_style_text_align(ui_ETA, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ETA, &ui_font_DINMedium14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_flash = lv_img_create(ui_Overview);
    lv_img_set_src(ui_flash, &ui_img_4_png);
    lv_obj_set_width(ui_flash, LV_SIZE_CONTENT);   /// 45
    lv_obj_set_height(ui_flash, LV_SIZE_CONTENT);    /// 45
    lv_obj_set_x(ui_flash, 124);
    lv_obj_set_y(ui_flash, 35);
    lv_obj_add_flag(ui_flash, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_flash, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_flash, 110);

    ui_Label2 = lv_label_create(ui_Overview);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 216);
    lv_obj_set_y(ui_Label2, 92);
    lv_label_set_text(ui_Label2, "Wh");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_GoogleSansMedium14, LV_PART_MAIN | LV_STATE_DEFAULT);

}
