// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Overview
void ui_Overview_screen_init(void);
lv_obj_t * ui_Overview;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Overview1;
lv_obj_t * ui_Charging;
lv_obj_t * ui_V;
lv_obj_t * ui_A;
lv_obj_t * ui_Percantage;
lv_obj_t * ui_Remaining;
lv_obj_t * ui_Voltage;
lv_obj_t * ui_Current;
lv_obj_t * ui_RSOC;
lv_obj_t * ui_Left;
lv_obj_t * ui_Capacity;
lv_obj_t * ui_OK;
lv_obj_t * ui_WARN;
lv_obj_t * ui_FAIL;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_ETA;
lv_obj_t * ui_flash;
lv_obj_t * ui_Label2;

// SCREEN: ui_Details
void ui_Details_screen_init(void);
lv_obj_t * ui_Details;
lv_obj_t * ui_Image1;
lv_obj_t * ui_Details1;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_[3] = {&ui_img_4_png, &ui_img_6_png, &ui_img_7_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Overview_screen_init();
    ui_Details_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Overview);
}
