// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Overview
void ui_Overview_screen_init(void);
extern lv_obj_t * ui_Overview;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Overview1;
extern lv_obj_t * ui_Charging;
extern lv_obj_t * ui_V;
extern lv_obj_t * ui_A;
extern lv_obj_t * ui_Percantage;
extern lv_obj_t * ui_Remaining;
extern lv_obj_t * ui_Voltage;
extern lv_obj_t * ui_Current;
extern lv_obj_t * ui_RSOC;
extern lv_obj_t * ui_Left;
extern lv_obj_t * ui_Capacity;
extern lv_obj_t * ui_OK;
extern lv_obj_t * ui_WARN;
extern lv_obj_t * ui_FAIL;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_ETA;
extern lv_obj_t * ui_flash;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_Details
void ui_Details_screen_init(void);
extern lv_obj_t * ui_Details;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Details1;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_4_png);    // assets\4.png
LV_IMG_DECLARE(ui_img_7_png);    // assets\7.png
LV_IMG_DECLARE(ui_img_6_png);    // assets\6.png

LV_FONT_DECLARE(ui_font_DINMedium14);
LV_FONT_DECLARE(ui_font_DINMedium16);
LV_FONT_DECLARE(ui_font_DINMedium32);
LV_FONT_DECLARE(ui_font_DINMedium34);
LV_FONT_DECLARE(ui_font_GoogleSansMedium10);
LV_FONT_DECLARE(ui_font_GoogleSansMedium12);
LV_FONT_DECLARE(ui_font_GoogleSansMedium13);
LV_FONT_DECLARE(ui_font_GoogleSansMedium14);
LV_FONT_DECLARE(ui_font_GoogleSansMedium15);
LV_FONT_DECLARE(ui_font_GoogleSansMedium16);
LV_FONT_DECLARE(ui_font_GoogleSansMedium22);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
